general {
    no_fade_in = true
    grace = 0
    disable_loading = true
    immediate_render = true
}
background {
    monitor =
    path = /home/paqarch/Pictures/1008514.jpg   # Ajuste para o seu wallpaper favorito
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 1 # 0 desativa o blur
}

# HORA
label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 64
    font_family = JetBrains Mono Nerd Font
    position = 0, 80
    halign = center
    valign = center
    update_interval = 1000 # Atualiza a cada 1 segundo (1000ms)
}

# CAMPO DE SENHA
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(151, 151, 151)
    inner_color = rgb(100, 100, 100)
    font_color = rgb(10, 10, 10)
    fade_on_empty = false
    placeholder_text = <i>Senha...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}
