general {
    lock_cmd = pidof swaylock || swaylock       # Alinhado para o swaylock-effects
    
    # Com o swaylock, você não precisa mais forçar o DPMS "on" antes de travar
    before_sleep_cmd = loginctl lock-session    
    
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms("on")'  # Mantido para garantir o sinal do monitor acordando
}

# 1. Escurecer a tela (após 2.5 min) - CONFIGURAÇÃO DO SEU MONITOR LG VIA DDCUTIL
listener {
    timeout = 150                                
    on-timeout = ddcutil setvcp 10 10 --bus 7        # Diminui o brilho para 10%
    on-resume = ddcutil setvcp 10 80 --bus 7         # Volta ao brilho normal (80%)
}

# 2. Bloquear a tela (após 5 min)
listener {
    timeout = 300                                
    on-timeout = loginctl lock-session           
}

# 3. Desligar o sinal do Monitor (após 5.5 min)
listener {
    timeout = 330                                
    on-timeout = hyprctl dispatch 'hl.dsp.dpms("off")'  # Desliga o sinal de vídeo
    on-resume = hyprctl dispatch 'hl.dsp.dpms("on")'    # Liga o sinal ao mexer o mouse / teclado
}

# 4. Suspender o PC (após 10 min)
listener {
    timeout = 600                                
    on-timeout = systemctl suspend               
}
